name: Deploy Model

on:
  repository_dispatch:
    types: [deploy_model]

permissions:
  actions: read
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read retrain flag
        id: read_flag
        run: echo "retrain=$(cut -d' ' -f1 state/retrain_flag.txt)" >> $GITHUB_OUTPUT

      - name: Stop if no retraining hapened
        if: ${{ steps.read_flag.outputs.retrain != 'true' }}
        run: echo "No retraining occurred â€” skipping deployment."

      - name: Download trained model artifact
        if: ${{ steps.read_flag.outputs.retrain == 'true' }}
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.client_payload.run_id }}
          name: trained-model
          path: api/models/

      - name: Commit and push updated model
        if: ${{ steps.read_flag.outputs.retrain == 'true' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add api/models/fraud_model.joblib
          git commit -m "Deploy updated model after retraining" || echo "No changes to commit"
          git push
